### ISSUE TITLE
Merge upstream changes.

### ISSUE THREAD

**Issue by SanskritFritz** [KarolBedkowski/kupfer-adds#6]
Please merge upstream changes.
https://git.gnome.org/browse/kupfer/log/

**Comment by KarolBedkowski** [comment]
Done.

**Comment by SanskritFritz** [comment]
Amazing, thanks. Do you plan to follow upstream changes? The best would be of course if they would merge your changes, but main development seems to be stalled right now. Did you send them a merge request? I personally consider your kupfer version as the best fork today.

**Comment by xHN35RQ** [comment]
>  I personally consider your kupfer version as the best fork today.

:+1: yes I agree, I'm glad I found your fork.
