### ISSUE TITLE
Push all the fixes to ppa Ubuntu >=16.04

### ISSUE THREAD

**Issue by khurshid-alam** [KarolBedkowski/kupfer-adds#7]
@KarolBedkowski 

Can you push all the fixes to PPA. The official version is 208 and its doesn't have these fixes. For example:

1. GTG api fixes (https://bugs.launchpad.net/kupfer/+bug/1093128)

2. Search Zim Notes: https://bugs.launchpad.net/kupfer/+bug/1506236

3. Evolution contacts: https://bugs.launchpad.net/kupfer/+bug/1312817 ; As python-evolution has deprecated, it is now better to use **libfolks/libfolks-eds25** or **gnome-contacts** itself which exposes eds functions on dbus.

Thanks

**Comment by KarolBedkowski** [comment]
I've pushed current version for Xenial. Not sure it is working.

Ad3 - Won't be fixed (by me) - sorry. If somebody prepare patch - I'll look on it.

**Comment by khurshid-alam** [comment]
@KarolBedkowski 

Thanks. It works!

I also filed a bug at [launchpad](https://bugs.launchpad.net/ubuntu/+source/kupfer/+bug/1600562). On the bug comment Hugo Lefeuvre wants to merge your patches at git.gnome and then pull releases from there into debian. May be you want to help with that. Thanks.
