### ISSUE TITLE
Can't compile on recent Mint install

### ISSUE THREAD

**Issue by igorsantos07** [KarolBedkowski/kupfer-adds#9]
It seems the `gio` package was renamed? https://askubuntu.com/a/91866

`./waf configure` complains about it, but simply installing `python-gobject python-gobject-2 python-gobject-2-dev` won't be enough.

I'm not versed at all with Python or Waf... I tried changing the import requirement to `gi`, but then it complains about missing `gtk` and I have no clue if that's replaceable - that SO answer implies that is also gone?

**Comment by KarolBedkowski** [comment]
This is legacy / python 2 version of Kupfer.
Version that support python3 is here:
https://github.com/KarolBedkowski/kupfer
or
https://github.com/kupferlauncher/kupfer
